import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import PrintableInvoice from '../components/PrintableInvoice';
import { ArrowLeft, Download, Loader2 } from 'lucide-react';
import { generateInvoice } from '../utils/invoiceGenerator';

const PublicInvoice = () => {
    const { id } = useParams();
    const [sale, setSale] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchSale = async () => {
            try {
                const response = await axios.get(`/api/transactions/public-sale/${id}`);
                setSale(response.data);
            } catch (err: any) {
                setError(err.response?.data?.message || 'Failed to load invoice');
            } finally {
                setLoading(false);
            }
        };
        fetchSale();
    }, [id]);

    if (loading) {
        return (
            <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
                <div className="flex flex-col items-center gap-4">
                    <Loader2 size={40} className="animate-spin text-primary-600" />
                    <p className="text-slate-500 font-bold uppercase tracking-widest text-[10px]">Loading Invoice...</p>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6 text-center">
                <div className="bg-white p-10 rounded-[3rem] shadow-xl border border-slate-100 max-w-md">
                    <div className="w-16 h-16 bg-rose-50 text-rose-500 rounded-3xl flex items-center justify-center mx-auto mb-6">
                        <ArrowLeft size={32} />
                    </div>
                    <h2 className="text-2xl font-black text-slate-800 tracking-tight mb-2">Invoice Not Found</h2>
                    <p className="text-slate-400 mb-8">{error}</p>
                    <a href="/" className="btn-primary inline-flex">Go to Home</a>
                </div>
            </div>
        );
    }

    const businessName = sale.tenantId?.companyName || 'BuildMate ERP';
    const ownerName = sale.tenantId?.name;

    return (
        <div className="min-h-screen bg-slate-50 pt-20 pb-10 px-4 md:px-0">
            {/* Header / Actions */}
            <div className="fixed top-0 left-0 right-0 bg-white/80 backdrop-blur-md border-b border-slate-100 z-50 p-4">
                <div className="max-w-2xl mx-auto flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-primary-600 text-white rounded-xl flex items-center justify-center font-black">B</div>
                        <h1 className="font-bold text-slate-800 truncate">{businessName}</h1>
                    </div>
                    <button 
                        onClick={() => generateInvoice(sale, businessName, ownerName)}
                        className="flex items-center gap-2 bg-slate-900 text-white px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-800 transition-all shadow-lg shadow-slate-200"
                    >
                        <Download size={14} /> Download PDF
                    </button>
                </div>
            </div>

            {/* Invoice Content */}
            <div className="max-w-2xl mx-auto">
                <div className="bg-white rounded-[2.5rem] shadow-[0_20px_60px_-15px_rgba(0,0,0,0.05)] border border-slate-100 p-8 md:p-12 overflow-hidden">
                    {/* Reuse PrintableInvoice but make it visible */}
                    <div className="block">
                        {/* We use the component but manually styling it for public view to avoid the 'hidden' class from index.css print rule */}
                        <div id="public-invoice-view">
                            <PrintableInvoice 
                                sale={sale} 
                                businessName={businessName} 
                                ownerName={ownerName} 
                            />
                        </div>
                    </div>
                </div>

                <div className="mt-8 text-center">
                    <p className="text-slate-400 text-[10px] font-bold uppercase tracking-[0.2em]">Generated by BuildMate ERP</p>
                </div>
            </div>

            {/* Inject custom style to force visibility of PrintableInvoice in this page */}
            <style>{`
                #public-invoice-view #printable-invoice {
                    display: block !important;
                    visibility: visible !important;
                }
            `}</style>
        </div>
    );
};

export default PublicInvoice;
