import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface CustomerItem {
  _id: string;
  name: string;
  unit: string;
  totalQuantity: number;
  totalAmount: number;
  firstPurchaseDate: string;
  lastPurchaseDate: string;
}

interface CustomerData {
  name: string;
  phone: string;
  address?: string;
}

export const generateCustomerItemsPDF = (customer: CustomerData, items: CustomerItem[], companyName: string = "BUILDMATE ERP") => {
  try {
    const doc = new jsPDF();

    // Calculate total amount spent on all items
    const grandTotal = items.reduce((sum, item) => sum + item.totalAmount, 0);

    // --- Header & Branding ---
    doc.setFillColor(30, 41, 59); // Slate-800
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(companyName.toUpperCase(), 15, 25);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Customer Purchased Items", 15, 32);
    
    doc.setFontSize(16);
    doc.text("PURCHASE HISTORY", 120, 25);

    // --- Customer Info Section ---
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Customer: ${customer.name.toUpperCase()}`, 15, 55);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    if (customer.phone) doc.text(`Phone: ${customer.phone}`, 15, 62);
    if (customer.address) doc.text(`Address: ${customer.address}`, 15, 68);
    
    doc.setFont("helvetica", "bold");
    doc.text(`Total Amount Spent: Rs. ${grandTotal.toLocaleString()}`, 120, 55);
    doc.text(`Total Unique Items: ${items.length}`, 120, 62);
    doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 120, 69);

    let currentY = 85;

    // --- Items Table ---
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Item Details", 15, currentY);

    const tableBody: any[] = items.map(item => [
      item.name,
      `${item.totalQuantity} ${item.unit}`,
      `Rs. ${item.totalAmount.toLocaleString()}`,
      new Date(item.firstPurchaseDate).toLocaleDateString(),
      new Date(item.lastPurchaseDate).toLocaleDateString()
    ]);

    autoTable(doc, {
      startY: currentY + 5,
      head: [['Product Name', 'Total Quantity', 'Total Amount', 'First Purchase', 'Last Purchase']],
      body: tableBody,
      headStyles: { fillColor: [30, 41, 59] },
      styles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 'auto' },
        1: { cellWidth: 30, halign: 'right' },
        2: { cellWidth: 30, halign: 'right' },
        3: { cellWidth: 30, halign: 'center' },
        4: { cellWidth: 30, halign: 'center' },
      }
    });

    currentY = (doc as any).lastAutoTable?.finalY + 30;

    // Page break if near bottom
    if (currentY > 260) {
      doc.addPage();
      currentY = 30;
    }

    // --- Footer ---
    doc.setLineWidth(0.5);
    doc.line(15, currentY, 70, currentY);
    doc.setFontSize(10);
    doc.text("Authorized Signature", 15, currentY + 5);
    
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by BuildMate ERP Management System", 75, 285);

    // Save PDF
    const fileName = `${customer.name.replace(/\s+/g, '_')}_Items.pdf`;
    doc.save(fileName);
    return true;
  } catch (error) {
    console.error('PDF Generation Error:', error);
    throw error;
  }
};
